"""部署亲和性（Deployment Affinity）检查。

确保携带 ``previous_response_id`` 的请求能够路由回生成该响应的原始部署，
维持会话连续性（session stickiness）。
"""

from __future__ import annotations

from typing import Any

from backend.response_id_codec import decode_response_id


def resolve_provider_for_previous_response(
    previous_response_id: str | None,
    available_providers: list[dict],
) -> dict | None:
    """根据 ``previous_response_id`` 解析应路由到的提供商。

    解码响应 ID 中的 ``custom_llm_provider`` 字段，并在 ``available_providers``
    列表中按 ``id`` 或 ``name`` 进行模糊匹配。

    Args:
        previous_response_id: 上一次响应的编码 ID。
        available_providers: 当前可用的提供商配置列表。

    Returns:
        匹配到的提供商字典；若无法匹配则返回 ``None``。
    """
    if not previous_response_id or not available_providers:
        return None

    decoded = decode_response_id(previous_response_id)
    provider_name = decoded.get("custom_llm_provider")
    if not provider_name:
        return None

    provider_name_lower = str(provider_name).lower()

    for provider in available_providers:
        if not isinstance(provider, dict):
            continue

        # 优先匹配 provider id
        pid = str(provider.get("id") or "").lower()
        if pid and pid == provider_name_lower:
            return provider

        # 其次匹配 provider name
        pname = str(provider.get("name") or "").lower()
        if pname and pname == provider_name_lower:
            return provider

    return None


def check_deployment_affinity(
    body: dict[str, Any],
    active_provider: dict | None,
    available_providers: list[dict],
) -> dict[str, Any]:
    """检查当前请求是否与历史响应的部署保持亲和性。

    逻辑：
    1. 若请求体中没有 ``previous_response_id``，直接放行（返回 success）。
    2. 解码 ``previous_response_id`` 提取原始 provider。
    3. 若原始 provider 与 ``active_provider`` 一致，放行。
    4. 若不一致，返回错误字典，建议客户端切换 provider。

    Args:
        body: 当前请求体（Responses API 格式）。
        active_provider: 当前选中的提供商配置。
        available_providers: 全部可用提供商列表（用于回退查找）。

    Returns:
        结果字典：
        - ``{"ok": True, "provider": active_provider}`` — 检查通过。
        - ``{"ok": False, "error": {...}, "suggested_provider": ...}`` — 不匹配。
    """
    previous_response_id = body.get("previous_response_id")
    if not previous_response_id:
        return {"ok": True, "provider": active_provider}

    if not active_provider:
        return {
            "ok": False,
            "error": {
                "type": "deployment_affinity_error",
                "message": "No active provider configured.",
            },
        }

    decoded = decode_response_id(str(previous_response_id))
    encoded_provider = decoded.get("custom_llm_provider")

    # 如果编码中没有 provider 信息，无法校验，直接放行
    if not encoded_provider:
        return {"ok": True, "provider": active_provider}

    # 判断 active_provider 是否匹配
    active_id = str(active_provider.get("id") or "").lower()
    active_name = str(active_provider.get("name") or "").lower()
    encoded_lower = str(encoded_provider).lower()

    matched = (
        active_id == encoded_lower
        or active_name == encoded_lower
        or encoded_lower in active_name
    )

    if matched:
        return {"ok": True, "provider": active_provider}

    # 尝试在可用列表中找到建议的 provider
    suggested = resolve_provider_for_previous_response(
        str(previous_response_id), available_providers
    )

    return {
        "ok": False,
        "error": {
            "type": "deployment_affinity_mismatch",
            "message": (
                f"Previous response was generated by provider '{encoded_provider}', "
                f"but current active provider is '{active_provider.get('name')}'. "
                "Please switch to the original provider to maintain session continuity."
            ),
            "encoded_provider": encoded_provider,
            "active_provider_id": active_provider.get("id"),
        },
        "suggested_provider": suggested,
    }
